apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-api
  name: deploy-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-api
    spec:
      containers:
      - image: prajwal3498/warehouseapi
        name: warehouseapi
        resources: {}
status: {}
