apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-api
  name: deploy-api
spec:
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: deploy-api
  type: NodePort
status:
  loadBalancer: {}
